---
title: Flux â€“ Upgrade Democracy
timezone: Australia/Sydney
collections:
  about:
    title: About
    output: true
  candidates:
    title: Candidates
    output: true
    permalink: "/candidates/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wa-team:
    title: WA Team
    output: true
  wa-posts:
    title: Posts
    output: true
  wa-candidates:
    title: WA Candidates
    output: true
email: website@voteflux.org
description: 'Flux is a new political party designed to connect Australians directly
  to Parliament and change politics forever!

'
baseurl:
url: https://voteflux.org
icon_path: img/social-icons/
accent-color: "#E3580D"
base-color: "#0b0b0e"
meetups: false
future: true
candidates: false
countdown: true
social-media:
- name: facebook
  url: https://facebook.com/voteflux.org
- name: twitter
  url: https://twitter.com/voteflux
- name: reddit
  url: https://www.reddit.com/r/voteflux
markdown: kramdown
permalink: pretty
incremental: true
exclude:
- node_modules
- README.md
- package.json
- gulpfile.js
- react-signup
- to-do
- signup.html
- npm-debug.log
- elm-stuff
- elmSrc
include:
  - _record_login_param.html
  - _redirects
plugins:
- jekyll-angular
redirects: true
strict_front_matter: true

exclude: ['_site', 'node_modules', '.git', '.bundle', '.bundle-gems', 'elm-stuff']

