---
title: Flux â€“ Upgrade Democracy
timezone: Australia/Sydney
collections:
  about:
    title: About
    output: true
  candidates:
    title: Candidates
    output: true
    permalink: "/candidates/:path/"
  candidates-nsw-2019:
    title: NSW Candidates 2019
    output: true
    permalink: "/nsw/candidates/2019/:name/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wa-team:
    title: WA Team
    output: true
  wa-posts:
    title: Posts
    output: true
  wa-candidates:
    title: WA Candidates
    output: true
defaults:
  - scope:
      path: ""
      type: "candidates-nsw-2019"
    values:
      layout: "candidate-v2"
email: website@voteflux.org
description: 'Flux is a new political party designed to connect Australians directly to Parliament and change politics forever!'
baseurl:
url: https://voteflux.org
icon_path: img/social-icons/
accent-color: "#E3580D"
base-color: "#0b0b0e"
meetups: false
future: true
candidates: false
countdown: true
social-media:
- name: facebook
  url: https://facebook.com/voteflux.org
- name: twitter
  url: https://twitter.com/voteflux
- name: reddit
  url: https://www.reddit.com/r/voteflux
markdown: kramdown
permalink: pretty
incremental: true
exclude:
  - README.md
  - package.json
  - gulpfile.js
  - node_modules
  - react-signup
  - to-do
  - signup.html
  - npm-debug.log
  - elm-stuff
  - elmSrc
  - .bundle-gems
  - .bundle
  - .git
  - _site
  - '*.sh'
  - 'Gemfile*'
  - elm-package.json
  - package-lock.json
  - yarn.lock
  - tsconfig.json
include:
  - _record_login_param.html
  - _redirects
plugins:
- jekyll-angular
redirects: true
strict_front_matter: true


